version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  video-transcode-go:
    lang: golang-middleware
    handler: ./video-transcode
    image: ghcr.io/rei-smz/video-transcode-go:latest
    environment:
      MINIO_ENDPOINT: "s3.128.110.217.96.nip.io:31644"
      BUCKET_NAME: "faas-bkt"
      exec_timeout: "30m"
      read_timeout: "30m"
      write_timeout: "30m"
    secrets:
      - minio-access-key
      - minio-secret-key
    requests:
      cpu: 11000m
    limits:
      cpu: 16000m

