version: 1.0
provider:
  name: openfaas
  gateway: 128.110.217.96.nip.io:31112
functions:
  video-detection:
    lang: python3-http-debian
    handler: ./video-detection
    image: ghcr.io/rei-smz/video-detection:latest
    build_args:
      ADDITIONAL_PACKAGE: "libgl1-mesa-glx libglib2.0-0"
    environment:
      MINIO_ENDPOINT: "s3.128.110.217.96.nip.io:31644"
      BUCKET_NAME: "faas-bkt"
      exec_timeout: "30m"
      read_timeout: "30m"
      write_timeout: "30m"
    secrets:
      - minio-access-key
      - minio-secret-key
    requests:
      cpu: 11000m
    limits:
      cpu: 16000m
